#!/usr/bin/expect -f


set force_conservative 0  ;# set to 1 to force conservative mode even if
			  ;# script wasn't run conservatively originally
if {$force_conservative} {
	set send_slow {1 .1}
	proc send {ignore arg} {
		sleep .1
		exp_send -s -- $arg
	}
}

set timeout -1
spawn $env(SHELL)
match_max 100000

expect "~\$ "
send -- "ssh  -i ~/.ssh/demo_tableau.pem hadoop@\$JAVIER_AWS_IP"
expect -exact " -i ~/.ssh/demo_tableau.pem hadoop@\$JAVIER_AWS_IP"
send -- "\r"
expect "~\$ "
send -- "hive\r"
expect "hive> "

foreach arg $argv {
	set file_name "$arg"
	set fp [open "$file_name" r]
	set file_data [read $fp]
	close $fp
	set data [split $file_data "\n"]
	foreach line $data {
		send -- "$line \r"
		expect "> "
	}
}
#send -- ""
#expect -exact "hadoop@ip-11-12-13-142:~\$ "
#send -- ""
#expect -exact "logout\r
#Connection to 123.1.2.2 closed.\r\r
#\]0;carlos@work: ~carlos@work:~\$ "
#send -- ""
#expect eof
